apiVersion: apps/v1
kind: Deployment
metadata:
  name: gradio-deployment-32b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gradio
  template:
    metadata:
      labels:
        app: gradio
    spec:
      containers:
      - name: gradio-container
        image: wdenniss/gradio-demo:latest
        ports:
        - containerPort: 7860
        env:
        - name: MODEL_ID
          value: deepseek-ai/DeepSeek-R1-Distill-Qwen-32B
        - name: MAX_TOKENS
          value: "30000"
        - name: PYTHONUNBUFFERED
          value: "1"
