apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-deployment-32b-a10080
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: vllm-32b-a10080
  template:
    metadata:
      labels:
        pod: vllm-32b-a10080
        app: vllm
    spec:
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-a100-80gb
        cloud.google.com/gke-spot: "true"
        cloud.google.com/gke-gpu-driver-version: latest
      containers:
      - name: vllm-container
        image: vllm/vllm-openai:v0.7.0
        command: ["python3", "-m", "vllm.entrypoints.openai.api_server"]
        args:
        - --model=$(MODEL_ID)
        - --trust-remote-code
        - --max-model-len=32016
        - --gpu-memory-utilization=0.95
        ports:
        - containerPort: 8000
        env:
        - name: MODEL_ID
          value: deepseek-ai/DeepSeek-R1-Distill-Qwen-32B
        - name: HUGGING_FACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-secret
              key: hf_api_token
        resources:
          limits:
            nvidia.com/gpu: 1
        volumeMounts:
        - name: hf-cache
          mountPath: /root/.cache/huggingface
      volumes:
      - name: hf-cache
        emptyDir: {}
